Feature/post view
Proximeety/ProximeetyApp pull request #114
Opened 2022-05-19 17:09 UTC by belengg27

2022-05-19 20:59 UTC, GuXiangTS approved these changes

2022-05-26 08:25 UTC, yanisdb requested changes
This is a good pull request, it seems to work very well.

On improvement could be if we could scroll down the list like on Instagram. If we click on someone's post, then we can keep scrolling his post but for now, it isn't necessary.

2022-05-26 08:25 UTC, yanisdb commented on app/src/main/java/ch/proximeety/proximeety/core/entities/Post.kt
> +    var postURL: String? = null,
You cannot change that. The class post has to be immutable other, it might cause a lot of confusion. Indeed, when we change a post object, the changes are not reflected to the Firebase, so it's better to no change them.
If you really want to change them, you can use `post.copy(postURL = "new_url")`.

2022-05-26 08:25 UTC, yanisdb commented on app/src/main/java/ch/proximeety/proximeety/core/entities/Post.kt
> +    var likes: Int,
Same here. Post has to be immutable.

2022-05-26 08:25 UTC, yanisdb commented on app/src/main/java/ch/proximeety/proximeety/core/entities/Post.kt
> +    var isLiked: Boolean = false
Same here. Post has to be immutable.

2022-05-26 08:52 UTC, yanisdb approved these changes

2022-05-26 10:02 UTC, merged